import { test, describe, beforeEach } from "node:test";
import { strict as assert } from "node:assert";

import { cleanCommitMessage } from "../bin/clean.js";
import { applyUserOverrides } from "../bin/prompts.js";

describe("cleanCommitMessage", () => {
  beforeEach(() => {
    applyUserOverrides({});
  });

  test("returns trimmed input when nothing matches", () => {
    assert.equal(cleanCommitMessage("feat: x\n\nbody\n"), "feat: x\n\nbody");
  });

  test("strips fenced code lines", () => {
    assert.equal(
      cleanCommitMessage("```\nfeat: x\n```\n"),
      "feat: x"
    );
  });

  test("strips Claude / Anthropic mentions case-insensitively", () => {
    const raw = "feat: x\nGenerated by claude\nAnthropic AI\nbody";
    assert.equal(cleanCommitMessage(raw), "feat: x\nbody");
  });

  test("strips Co-Authored-By and Signed-off-by lines", () => {
    const raw = "feat: x\n\nCo-Authored-By: foo\nSigned-off-by: bar\nbody";
    assert.equal(cleanCommitMessage(raw), "feat: x\n\nbody");
  });

  test("strips 'Here is the commit message' preface", () => {
    const raw = "Here is the commit message:\nfeat: x\nbody";
    assert.equal(cleanCommitMessage(raw), "feat: x\nbody");
  });

  test("stops at 'Wait, the rules said...' lines", () => {
    const raw = "feat: x\nbody\nWait, the rules said no markdown\nmore junk";
    assert.equal(cleanCommitMessage(raw), "feat: x\nbody");
  });

  test("respects user override removeLinesMatching (replace semantics)", () => {
    applyUserOverrides({ removeLinesMatching: ["^INTERNAL:"] });
    const raw = "feat: x\nINTERNAL: secret\nClaude wrote this\nbody";
    // 'Claude' line should NOT be stripped because user replaced defaults
    assert.equal(
      cleanCommitMessage(raw),
      "feat: x\nClaude wrote this\nbody"
    );
  });

  test("respects user override stopLinesMatching", () => {
    applyUserOverrides({ stopLinesMatching: ["^END$"] });
    const raw = "feat: x\nbody\nEND\nshould be gone";
    assert.equal(cleanCommitMessage(raw), "feat: x\nbody");
  });

  test("empty input returns empty string", () => {
    assert.equal(cleanCommitMessage(""), "");
  });

  test("returns empty when all lines match remove patterns", () => {
    assert.equal(cleanCommitMessage("Claude\nAnthropic\n"), "");
  });
});
